In [1]:
import numpy as np

In [2]:
u = np.array([1., 2., 3.])
v = np.array([4., 5., 6.])

In [3]:
u + v

array([5., 7., 9.])

In [4]:
u - v

array([-3., -3., -3.])

In [5]:
v[0]

np.float64(4.0)

In [6]:
v[1]

np.float64(5.0)

In [7]:
2 * u

array([2., 4., 6.])

In [8]:
v / 3

array([1.33333333, 1.66666667, 2.        ])

In [9]:
np.linalg.norm(u)

np.float64(3.7416573867739413)